### PR TITLE
New dropdowns and tweaks

### PR DESCRIPTION
**Pull request by moreofmorris**
### Purpose
New dropdown styling and many other small design tweaks. I'm really sorry that this wasn't broken out into small pull requests, I think I got a little carried away 🙃  I've also added a new Export Picker component.

### Notes
This has a new Export Picker component. There are many attempts to start stripping away LESS from some components and adding in styled-components whilst I was working. I'm afraid I got carried away and it's a pretty big pull request. I need to still work on the Date Picker custom area. It's not looking great yet but I'll continue on with that later.

### Review
Hey @msanroman. It'd be great to get your eyes on this! 👍 

#### Staging Deployment

_This repo is CI/CD enabled and staging deployment should be available at:
https://task-new-dropdowns-and-tweaks-analyze.dev.buffer.com/ :smile:_

### CODE REVIEW

**Comment by moreofmorris** [comment]
There seems to be some coverage issues @msanroman ? Is that because I've added a new component and that's brought down the average a bit? 🤔

**Comment by msanroman** [comment]
Hey @moreofmorris! I see you removed the `Subtitle` reference on DatePickerButton, and that has caused a decrease of code coverage since you still have in the `Titles.jsx` the whole `Subtitle` component code.

I am wondering if that removal was intended? [That component is the one that shows the actual dates for the selected date range](https://cl.ly/1C3S203O0H1x/Image%202017-11-24%20at%203.46.36%20PM.png).

If we are no longer going to use it, we should also remove its code from `Titles.jsx`.

Also, are we okay with having the date picker displayed [like this](https://cl.ly/3u3S1O3D2f1b/Image%202017-11-24%20at%203.47.59%20PM.png) if we merge this PR? Just want to make sure we are :)

**Comment by moreofmorris** [comment]
You're right @msanroman. I forgot that it actually looked that bad. I wanted to do more work to it, but it slipped through my thoughts. I'll tidy this up a bit more and push again! 👍

**Comment by moreofmorris** [comment]
Hey there @tiggreen ... this is a pretty big pull request with lots of little changes everywhere. Mike has seen it a few times and I think we're pretty much ok to go but I'm stuck personally getting this codecov/patch test pass to be successful. Not quite sure how to fix this as I haven't encounted it before. No rush on this, but would love some eyes on it so I can merge this pull request into master! :)

**Comment by tiggreen** [comment]
Hey @moreofmorris I've added dispatch tests for date-picker but since it's quite big PR it feels good to merge and ignore the coverage report for now! :) I think we will need to tweak Codecov anyway.

**Comment by moreofmorris** [comment]
Thank you @tiggreen, that's awesome. And I'll keep the pull requests down in the future. This one definitely got out of hand 😆 Thanks so much for your time on this 👍

**Pull request merged**
