### PR TITLE
Improve reports appearance

### PR DESCRIPTION
**Pull request by moreofmorris**
### Purpose
This is to try and improve the appearance of the reports with stronger and cleaner lines with tighter spacing. Though this is just a minor improvement now, more will follow.

### Notes
Though visually it doesn't look like too much of a difference there are many subtle things in play. I've also refactored the chart titles so there is one place where it is generated. Each chart still has it's own title component but it's made from a base component that's now in the shared components. I needed a way for the chart titles to know that it's from a report. Over the next week, I'll be continuing to experiment with styling for the reports and it's clear I need a way to tell the charts that it's being displayed for the app or for a report. I've added in some new profile badges for reports. I've attempted to also include these for comparison charts that are added to the report. I've also fixed a bug with editing the report title where it didn't focus on the text box when clicked and you can now press enter to submit the change.

### Review
Yo @msanroman, it seems to make sense that you'll be the best person to review this.

#### Staging Deployment
_This repo is CI/CD enabled and staging deployment should be available at:
https://task-improved-reports-appearance-analyze.dev.buffer.com :smile:_

### CODE REVIEW

**Comment by moreofmorris** [comment]
Yo @msanroman, I've added you to this pull request as it's to do with reports. I'd love some eyes on it.

**Comment by moreofmorris** [comment]
I still don't really understand how to get code coverage to pass. I'm not really sure how to diagnose it or what to really do to help it pass. I've had this problem on a few pull requests it seems! 👍

**Comment by moreofmorris** [comment]
I'm going to keep working on getting the code coverage to pass @msanroman but I'd love to start getting your eyes on this as I know this is a fairly biggish pull request. I've tried to put in place some groundwork so I can iterate faster with style changes over the coming weeks (hence the `forReport` stuff to make the chart headers dynamic depending if they're in the app or in the report). Love some eyes on it when you get a bit of time 👍

**Comment by federicoweber** [comment]
hey @moreofmorris, I've added a few integration tests that leverage Enzyme to simulate and test components actions :smile:. 

I think this is a good strategy to test the expected behavior of React components; another option could have been to export the actions and test those in isolation with dedicated unit tests.

**Comment by moreofmorris** [comment]
Thanks so much for your help @federicoweber!

**Pull request merged**
