### PR TITLE
Add Headway widget to the Dashboard page

### PR DESCRIPTION
**Pull request by moreofmorris**
### Purpose
This adds the useful Headway widget to our Dashboard page. This will allow us to share big and small updates to our customers directly from within the app without having to always resort to emails for changes. Sending email updates to customers is still very much a thing! But there are lots of other little updates too that we could easily share to show momentum with something like the Headway widget.

### Notes
This was surprisingly difficult to implement. There are lots of little quirks that aren't explained fully in the docs of the widget. I've tried to keep this code as clean as possible for the desired results.

### Staging
Check this out here: https://task-add-headway-to-dashboard-analyze.dev.buffer.com/

### CODE REVIEW

**Comment by moreofmorris** [comment]
Hello @tiggreen! 👋This is a lower priority pull request. It adds in the Headway widget for the Dashboard. I'm afraid I don't know why the Codecov is flagging this as a problem (I still don't really understand it too well). But I hope the code looks ok aside from this? 🤔

**Comment by moreofmorris** [comment]
Hey there @tiggreen, sorry, I know you're busy. Just thought I'd bump this just in case it fell through the cracks. There's no rush on this BTW! :)

**Comment by tiggreen** [comment]
Going to review now @moreofmorris

**Comment by moreofmorris** [comment]
Thank you very much @tiggreen 👍

**Pull request merged**
