### PR TITLE
Add performance middleware

### PR DESCRIPTION
**Pull request by federicoweber**
### Purpose
To adds `performance-tracking` middleware. 
The middleware is a wrapper around [@bufferapp/chronos](https://github.com/bufferapp/buffer-js-chronos) APIs and exposes Chronos methods via action creators.

You can use it like this
```
store.dispatch(performanceActions.startMeasure({ name: 'foo' }));
…
store.dispatch(performanceActions.stopMeasure({ name: 'foo' }));
```

#### Staging Deployment

_This repo is CI/CD enabled and staging deployment should be available at:
https://<branch_name>.analyze.buffer.com :smile:_

### CODE REVIEW

**Comment by federicoweber** [comment]
hey @msanroman :smile:, just wanted to put this on your radar, but no rush in reviewing this: I going to add in a few more test cases before merging it in.

**Comment by federicoweber** [comment]
hey @msanroman, I think this is ready to merge in if it looks good to you too :smile:.

**Comment by tiggreen** [comment]
When we have `task/do-something-awesome` branch what would be the URL to the staging? `https://do-something-awesome.analyze.buffer.com 😄`?

**Comment by msanroman** [comment]
Ah @tiggreen, it'd be `https://task-do-something-awesome.analyze.buffer.com` 😄

**Pull request merged**
